/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as appContactRouteImport } from './routes/(app)/contact'
import { Route as appAboutRouteImport } from './routes/(app)/about'
import { Route as AdminProductRouteRouteImport } from './routes/admin/product/route'
import { Route as AdminCategoryRouteRouteImport } from './routes/admin/category.route'
import { Route as authAuthRouteRouteImport } from './routes/(auth)/auth.route'
import { Route as AdminProductCreateProductRouteImport } from './routes/admin/product/create-product'
import { Route as AdminProductAllProductsRouteImport } from './routes/admin/product/all-products'
import { Route as AdminCategoryCreateNewCategoryRouteImport } from './routes/admin/category.create-new-category'
import { Route as AdminCategoryAllCategoriesRouteImport } from './routes/admin/category.all-categories'
import { Route as authAuthSignupRouteImport } from './routes/(auth)/auth.signup'
import { Route as authAuthLoginRouteImport } from './routes/(auth)/auth.login'
import { Route as appShopProductsRouteImport } from './routes/(app)/shop/products'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const appContactRoute = appContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => appRouteRoute,
} as any)
const appAboutRoute = appAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => appRouteRoute,
} as any)
const AdminProductRouteRoute = AdminProductRouteRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoryRouteRoute = AdminCategoryRouteRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => AdminRouteRoute,
} as any)
const authAuthRouteRoute = authAuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => authRouteRoute,
} as any)
const AdminProductCreateProductRoute =
  AdminProductCreateProductRouteImport.update({
    id: '/create-product',
    path: '/create-product',
    getParentRoute: () => AdminProductRouteRoute,
  } as any)
const AdminProductAllProductsRoute = AdminProductAllProductsRouteImport.update({
  id: '/all-products',
  path: '/all-products',
  getParentRoute: () => AdminProductRouteRoute,
} as any)
const AdminCategoryCreateNewCategoryRoute =
  AdminCategoryCreateNewCategoryRouteImport.update({
    id: '/create-new-category',
    path: '/create-new-category',
    getParentRoute: () => AdminCategoryRouteRoute,
  } as any)
const AdminCategoryAllCategoriesRoute =
  AdminCategoryAllCategoriesRouteImport.update({
    id: '/all-categories',
    path: '/all-categories',
    getParentRoute: () => AdminCategoryRouteRoute,
  } as any)
const authAuthSignupRoute = authAuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authAuthRouteRoute,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authAuthRouteRoute,
} as any)
const appShopProductsRoute = appShopProductsRouteImport.update({
  id: '/shop/products',
  path: '/shop/products',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof authAuthRouteRouteWithChildren
  '/admin/category': typeof AdminCategoryRouteRouteWithChildren
  '/admin/product': typeof AdminProductRouteRouteWithChildren
  '/about': typeof appAboutRoute
  '/contact': typeof appContactRoute
  '/': typeof appIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/shop/products': typeof appShopProductsRoute
  '/auth/login': typeof authAuthLoginRoute
  '/auth/signup': typeof authAuthSignupRoute
  '/admin/category/all-categories': typeof AdminCategoryAllCategoriesRoute
  '/admin/category/create-new-category': typeof AdminCategoryCreateNewCategoryRoute
  '/admin/product/all-products': typeof AdminProductAllProductsRoute
  '/admin/product/create-product': typeof AdminProductCreateProductRoute
}
export interface FileRoutesByTo {
  '/auth': typeof authAuthRouteRouteWithChildren
  '/admin/category': typeof AdminCategoryRouteRouteWithChildren
  '/admin/product': typeof AdminProductRouteRouteWithChildren
  '/about': typeof appAboutRoute
  '/contact': typeof appContactRoute
  '/': typeof appIndexRoute
  '/admin': typeof AdminIndexRoute
  '/shop/products': typeof appShopProductsRoute
  '/auth/login': typeof authAuthLoginRoute
  '/auth/signup': typeof authAuthSignupRoute
  '/admin/category/all-categories': typeof AdminCategoryAllCategoriesRoute
  '/admin/category/create-new-category': typeof AdminCategoryCreateNewCategoryRoute
  '/admin/product/all-products': typeof AdminProductAllProductsRoute
  '/admin/product/create-product': typeof AdminProductCreateProductRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/(auth)/auth': typeof authAuthRouteRouteWithChildren
  '/admin/category': typeof AdminCategoryRouteRouteWithChildren
  '/admin/product': typeof AdminProductRouteRouteWithChildren
  '/(app)/about': typeof appAboutRoute
  '/(app)/contact': typeof appContactRoute
  '/(app)/': typeof appIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/(app)/shop/products': typeof appShopProductsRoute
  '/(auth)/auth/login': typeof authAuthLoginRoute
  '/(auth)/auth/signup': typeof authAuthSignupRoute
  '/admin/category/all-categories': typeof AdminCategoryAllCategoriesRoute
  '/admin/category/create-new-category': typeof AdminCategoryCreateNewCategoryRoute
  '/admin/product/all-products': typeof AdminProductAllProductsRoute
  '/admin/product/create-product': typeof AdminProductCreateProductRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/auth'
    | '/admin/category'
    | '/admin/product'
    | '/about'
    | '/contact'
    | '/'
    | '/admin/'
    | '/shop/products'
    | '/auth/login'
    | '/auth/signup'
    | '/admin/category/all-categories'
    | '/admin/category/create-new-category'
    | '/admin/product/all-products'
    | '/admin/product/create-product'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin/category'
    | '/admin/product'
    | '/about'
    | '/contact'
    | '/'
    | '/admin'
    | '/shop/products'
    | '/auth/login'
    | '/auth/signup'
    | '/admin/category/all-categories'
    | '/admin/category/create-new-category'
    | '/admin/product/all-products'
    | '/admin/product/create-product'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)'
    | '/admin'
    | '/(auth)/auth'
    | '/admin/category'
    | '/admin/product'
    | '/(app)/about'
    | '/(app)/contact'
    | '/(app)/'
    | '/admin/'
    | '/(app)/shop/products'
    | '/(auth)/auth/login'
    | '/(auth)/auth/signup'
    | '/admin/category/all-categories'
    | '/admin/category/create-new-category'
    | '/admin/product/all-products'
    | '/admin/product/create-product'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/contact': {
      id: '/(app)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof appContactRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/about': {
      id: '/(app)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof appAboutRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/admin/product': {
      id: '/admin/product'
      path: '/product'
      fullPath: '/admin/product'
      preLoaderRoute: typeof AdminProductRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/category': {
      id: '/admin/category'
      path: '/category'
      fullPath: '/admin/category'
      preLoaderRoute: typeof AdminCategoryRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(auth)/auth': {
      id: '/(auth)/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof authAuthRouteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/admin/product/create-product': {
      id: '/admin/product/create-product'
      path: '/create-product'
      fullPath: '/admin/product/create-product'
      preLoaderRoute: typeof AdminProductCreateProductRouteImport
      parentRoute: typeof AdminProductRouteRoute
    }
    '/admin/product/all-products': {
      id: '/admin/product/all-products'
      path: '/all-products'
      fullPath: '/admin/product/all-products'
      preLoaderRoute: typeof AdminProductAllProductsRouteImport
      parentRoute: typeof AdminProductRouteRoute
    }
    '/admin/category/create-new-category': {
      id: '/admin/category/create-new-category'
      path: '/create-new-category'
      fullPath: '/admin/category/create-new-category'
      preLoaderRoute: typeof AdminCategoryCreateNewCategoryRouteImport
      parentRoute: typeof AdminCategoryRouteRoute
    }
    '/admin/category/all-categories': {
      id: '/admin/category/all-categories'
      path: '/all-categories'
      fullPath: '/admin/category/all-categories'
      preLoaderRoute: typeof AdminCategoryAllCategoriesRouteImport
      parentRoute: typeof AdminCategoryRouteRoute
    }
    '/(auth)/auth/signup': {
      id: '/(auth)/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof authAuthSignupRouteImport
      parentRoute: typeof authAuthRouteRoute
    }
    '/(auth)/auth/login': {
      id: '/(auth)/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof authAuthRouteRoute
    }
    '/(app)/shop/products': {
      id: '/(app)/shop/products'
      path: '/shop/products'
      fullPath: '/shop/products'
      preLoaderRoute: typeof appShopProductsRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appAboutRoute: typeof appAboutRoute
  appContactRoute: typeof appContactRoute
  appIndexRoute: typeof appIndexRoute
  appShopProductsRoute: typeof appShopProductsRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAboutRoute: appAboutRoute,
  appContactRoute: appContactRoute,
  appIndexRoute: appIndexRoute,
  appShopProductsRoute: appShopProductsRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authAuthRouteRouteChildren {
  authAuthLoginRoute: typeof authAuthLoginRoute
  authAuthSignupRoute: typeof authAuthSignupRoute
}

const authAuthRouteRouteChildren: authAuthRouteRouteChildren = {
  authAuthLoginRoute: authAuthLoginRoute,
  authAuthSignupRoute: authAuthSignupRoute,
}

const authAuthRouteRouteWithChildren = authAuthRouteRoute._addFileChildren(
  authAuthRouteRouteChildren,
)

interface authRouteRouteChildren {
  authAuthRouteRoute: typeof authAuthRouteRouteWithChildren
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authAuthRouteRoute: authAuthRouteRouteWithChildren,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AdminCategoryRouteRouteChildren {
  AdminCategoryAllCategoriesRoute: typeof AdminCategoryAllCategoriesRoute
  AdminCategoryCreateNewCategoryRoute: typeof AdminCategoryCreateNewCategoryRoute
}

const AdminCategoryRouteRouteChildren: AdminCategoryRouteRouteChildren = {
  AdminCategoryAllCategoriesRoute: AdminCategoryAllCategoriesRoute,
  AdminCategoryCreateNewCategoryRoute: AdminCategoryCreateNewCategoryRoute,
}

const AdminCategoryRouteRouteWithChildren =
  AdminCategoryRouteRoute._addFileChildren(AdminCategoryRouteRouteChildren)

interface AdminProductRouteRouteChildren {
  AdminProductAllProductsRoute: typeof AdminProductAllProductsRoute
  AdminProductCreateProductRoute: typeof AdminProductCreateProductRoute
}

const AdminProductRouteRouteChildren: AdminProductRouteRouteChildren = {
  AdminProductAllProductsRoute: AdminProductAllProductsRoute,
  AdminProductCreateProductRoute: AdminProductCreateProductRoute,
}

const AdminProductRouteRouteWithChildren =
  AdminProductRouteRoute._addFileChildren(AdminProductRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminCategoryRouteRoute: typeof AdminCategoryRouteRouteWithChildren
  AdminProductRouteRoute: typeof AdminProductRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCategoryRouteRoute: AdminCategoryRouteRouteWithChildren,
  AdminProductRouteRoute: AdminProductRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
